ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_prov_id
ALTER TABLE Treatment DROP CONSTRAINT FK_Treatment_patient_id
ALTER TABLE DRUGTREATMENT DROP CONSTRAINT FK_DRUGTREATMENT_ID
ALTER TABLE RADIOLOGY DROP CONSTRAINT FK_RADIOLOGY_ID
ALTER TABLE SURGERY DROP CONSTRAINT FK_SURGERY_ID
ALTER TABLE Radiology_RADIOLOGYDATES DROP CONSTRAINT FK_Radiology_RADIOLOGYDATES_Radiology_ID
DROP TABLE Patient CASCADE
DROP TABLE Treatment CASCADE
DROP TABLE DRUGTREATMENT CASCADE
DROP TABLE RADIOLOGY CASCADE
DROP TABLE SURGERY CASCADE
DROP TABLE Provider CASCADE
DROP TABLE Radiology_RADIOLOGYDATES CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
